#ifndef ROADTYPES
#define ROADTYPES

typedef enum {
   //All the possible OSM Road Types
   INVALID=0,
   MOTORWAY, TRUNK, PRIMARY, SECONDARY, TERTIARY,
   UNCLASSIFIED, RESIDENTIAL, SERVICE,
   MOTORWAY_LINK, TRUNK_LINK, PRIMARY_LINK, SECONDARY_LINK, TERTIARY_LINK,
   LIVING_STREET, PEDESTRIAN, TRACK,
   BUS_GUIDE_WAY, RACEWAY, ROAD,
   FOOTWAY, BRIDLEWAY, STEPS, PATH,
   CYCLEWAY, BUS_STOP, PLATORM
} EdgeType;



#endif // ROADTYPES

